### PR TITLE
fix: pipeline/inference.to(device) supports only touch.device

### LINKED ISSUE #1397: pipeline.to(str|int) raise AttributeError device.type in fix_reproducibility
https://github.com/pyannote/pyannote-audio/issues/1354#issuecomment-1572030629

> ```python
>  pipeline = Pipeline.from_pretrained( 'pyannote/speaker-diarization', use_auth_token='your_token_here') 
>  pipeline = pipeline.to(0)
>  ```
>  
>  I get the following error : 
>  
>  ```python
>  Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/ec2-user/anaconda3/envs/whisper/lib/python3.9/site-packages/pyannote/audio/core/pipeline.py", line 297, in __call__
>     fix_reproducibility(getattr(self, "device", torch.device("cpu")))
>   File "/home/ec2-user/anaconda3/envs/whisper/lib/python3.9/site-packages/pyannote/audio/utils/reproducibility.py", line 69, in fix_reproducibility
>     if (device.type == "cuda") and (
> AttributeError: 'int' object has no attribute 'type'
> ```

### PR DESCRIPTION
**Pull request by chai3**
fix #1397

### CODE REVIEW

**Comment by hbredin** [comment]
Thanks! Yes, please do the same for every similar `.to()` methods. Thanks!

**Comment by chai3** [comment]
@hbredin I fixed similar

**Comment by hbredin** [comment]
Thanks. One last thing. Can you please update the error message from 
```
device must be torch.device
``` 
to 
```
`device` must be an instance of `torch.device`
```

After that, I think we are all good!

**Comment by chai3** [comment]
@hbredin I updated the error message

**Comment by hbredin** [comment]
Merged! Will be part of next release. Thanks! :tada:

**Pull request merged**
