### PR TITLE
Fix missing install candidate for ONNX Runtime on Apple Silicon

### LINKED ISSUE #1505: Sadly onnxruntime-gpu dependency kills Mac support
Hi, thanks for the great package. Sadly the recently (3.0.1) introduced `onnxruntime-gpu` dependency kills Mac support. At least on M2 (didn't try anything else).

**Describe the solution you'd like**
- platform depended requirements? ([onnxruntime-silicon](https://github.com/cansik/onnxruntime-silicon ?)
- go back to `onnxruntime`?

### PR DESCRIPTION
**Pull request by dr-duplo**
This patch alters the requirements to use another ONNX runtime package which provides pre-build wheels for Apple Silicon in case of running on arm64/M1/M2 Mac.

Fixes #1505

### CODE REVIEW

**Comment by hbredin** [comment]
PR is failing build tests. Can you please check?

**Comment by dr-duplo** [comment]
> PR is failing build tests. Can you please check?

It seems like `macos-latest` is on `macos-12` and`x86_64` arch. This clashes with `onnxruntime-silicon` which only provides `macosx_13_0_arm64`wheels. That being said, `onnxruntime-gpu` only provides `x86_64` and `amd64` wheels for linux and windows. @hbredin I wonder how you can use `onnxruntime-gpu` on your M1.

**Comment by stygmate** [comment]
I have tried this patch, it work for me, but my macstudio m1 GPU is not used. (i correctly set torch to mps backend)
any thougts about this ?

**Comment by dr-duplo** [comment]
> I have tried this patch, it work for me, but my macstudio m1 GPU is not used. (i correctly set torch to mps backend) any thougts about this ?

Which MacOS version are you running?

**Comment by stygmate** [comment]
@dr-duplo 

> Which MacOS version are you running?

13.6.1

**Comment by dr-duplo** [comment]
> @dr-duplo
> 
> > Which MacOS version are you running?
@stygmate  
> 13.6.1

At least this proves it installs on Ventura. Did you experience just speed degradation like in https://github.com/pytorch/pytorch/issues/77799 or did you prove the M1 GPU was not used?

**Comment by stygmate** [comment]
@dr-duplo when running this

```python
import torch
import timeit

b_cpu = torch.rand((10000, 10000), device='cpu')
b_mps = torch.rand((10000, 10000), device='mps')

print('cpu', timeit.timeit(lambda: b_cpu @ b_cpu, number=100))
print('mps', timeit.timeit(lambda: b_mps @ b_mps, number=100))
```

i get:

```
cpu 100.59644954199939
mps 12.907685874999515
```

For pyannote, when settings pipeline to cpu:
- all stages of the pipeline are slow
- the evaluated time for embeddings process (for 1h21 of audio) is ~1h

when settings pipeline to mps:
- the two first stages of the pipeline are really fast
- the evaluated time for embeddings process is ~1h (the same as for cpu processing)

so GPU don't seem to be used.

**Comment by dr-duplo** [comment]
@stygmate 
I'm not a pyannote expert, but the code tells me that only the speaker embeddings computation is gpu accelerated, but the speaker clustering, which computes the final speaker embedding afterwards, is not. Maybe this is the source for the long processing time.

**Comment by stygmate** [comment]
@dr-duplo Hier I discovered that in the Pyannote code the Onnxruntime execution provider (CoreMLExecutionProvider) corresponding to the Torch mps device was not set.

I added it:

```diff
Index: pyannote/audio/pipelines/speaker_verification.py
@@ -455,6 +455,8 @@
                     },
                 )
             ]
+        if device.type == "mps":
+            providers = ["CoreMLExecutionProvider"]
         else:
             warnings.warn(
                 f"Unsupported device type: {device.type}, falling back to CPU"
```

But the MPS backend does not support FFT operators and it crashes 😩🔫

**Comment by hbredin** [comment]
FYI: https://github.com/pyannote/pyannote-audio/issues/1537

**Comment by hbredin** [comment]
Closing as pyannote 3.1 will get rid of this ONNX mess.

**Pull request closed without merging**
