### PR TITLE
concatenation of adjacent MFCCs in Yaafe

### PR DESCRIPTION
**Pull request by yinruiqing**
add a new configuration in Yaafe extractor: concatenate adjacent MFCCs

### CODE REVIEW

**Comment by hbredin** [comment]
Thanks. Can you give me write access to your pull request?
I would like to make a few changes (mostly cosmetic) before merging it. 
See https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/ for details on how to do that.

**Comment by yinruiqing** [comment]
Hi, it has been done.

**Comment by hbredin** [comment]
I pushed a commit to your pull request.
I renamed `num_concatenate` to `stack`.

Can you check this is still working as you expect it to work?

**Comment by yinruiqing** [comment]
Hi, I've checked. It works as I expect.

**Pull request merged**
