### PR TITLE
refactor: switch to pytorch-lightning

### PR DESCRIPTION
**Pull request by hbredin**
Let's try this `PyTorch Lightning` thing!

### CODE REVIEW

**Comment by hbredin** [comment]
- [ ] support for data augmentation
- [ ] support for `--pretrained` option
- [ ] multi-GPU training
- [ ] re-train (and share) all pyannote-audio-hub models

**Comment by mogwai** [comment]
Need any help with this? I'm interested in learning more about speaker diarization and see this refactor as a way of learning how it works.

**Comment by hbredin** [comment]
> Need any help with this? I'm interested in learning more about speaker diarization and see this refactor as a way of learning how it works.

I'd definitely need help with this. Thanks! It is taking way longer than I originally expected! 

I'd need to find some time to make a proper list of what needs to be done first.
But, in the meantime, maybe you could try to follow the tutorials (from the `pytorch-lightning` branch) and report when things don't work as they should. What do you think?

**Comment by mogwai** [comment]
Sounds good to me, I'll get started

**Comment by mogwai** [comment]
The `data_preparation` tutorial seems fine. I'm trying to run a pretrained inference pipeline but having issues with the torch hub models:
```py
import torch
pipeline = torch.hub.load('pyannote/pyannote-audio', 'dia')
diarization = pipeline(DEMO_FILE)
```
```py
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-9d800f4ee0ec> in <module>
      1 import torch
----> 2 pipeline = torch.hub.load('pyannote/pyannote-audio', 'dia')
      3 diarization = pipeline(DEMO_FILE)

~/miniconda3/envs/pyannote-audio/lib/python3.7/site-packages/torch/hub.py in load(github, model, *args, **kwargs)
    351     entry = _load_entry_from_hubconf(hub_module, model)
    352 
--> 353     model = entry(*args, **kwargs)
    354 
    355     sys.path.remove(repo_dir)

~/.cache/torch/hub/pyannote_pyannote-audio_master/hubconf.py in _generic(name, duration, step, batch_size, device, pipeline, force_reload)
    242         from pyannote.audio.pipeline.utils import load_pretrained_pipeline
    243         params_yml, *_ = pretrained_subdir.glob('*/*/params.yml')
--> 244         return load_pretrained_pipeline(params_yml.parent)
    245 
    246 with open(_PRETRAINED_YML, 'r') as fp:

~/work/pyannote-audio/pyannote/audio/pipeline/utils.py in load_pretrained_pipeline(train_dir)
     90         pipeline_name, default_module_name="pyannote.audio.pipeline"
     91     )
---> 92     pipeline = Klass(**config["pipeline"].get("params", {}))
     93 
     94     return pipeline.load_params(train_dir / "params.yml")

~/work/pyannote-audio/pyannote/audio/pipeline/speaker_diarization.py in __init__(self, sad_scores, scd_scores, embedding, metric, method, evaluation_only, purity)
    120         else:
    121             self.speech_turn_segmentation = SpeechTurnSegmentation(
--> 122                 sad_scores=self.sad_scores, scd_scores=self.scd_scores
    123             )
    124         self.evaluation_only = evaluation_only

~/work/pyannote-audio/pyannote/audio/pipeline/speech_turn_segmentation.py in __init__(self, sad_scores, scd_scores, non_speech, purity)
     99         else:
    100             self.speech_activity_detection = SpeechActivityDetection(
--> 101                 scores=self.sad_scores
    102             )
    103 

~/work/pyannote-audio/pyannote/audio/pipeline/speech_activity_detection.py in __init__(self, scores, fscore, hysteresis)
    102             scores = "@sad_scores"
    103         self.scores = scores
--> 104         self._scores = Wrapper(self.scores)
    105 
    106         self.fscore = fscore

~/work/pyannote-audio/pyannote/audio/features/wrapper.py in __init__(self, wrappable, **params)
    221         # warn the user the something went wrong
    222         if scorer is None:
--> 223             raise ValueError(msg)
    224 
    225         self.scorer_ = scorer

ValueError: Could not load sad_dihard model from torch.hub. The following exception was raised:
Could not infer module name from class name "SpeechActivityDetection".Please provide default module name.

```

**Comment by mogwai** [comment]
This can be closed now?

**Pull request closed without merging**
