### PR TITLE
feat: reproduce original segmentation results

### PR DESCRIPTION
**Pull request by hbredin**
In this branch, I will try to train segmentation (VAD, SCD, OSD) models to check if we can reach (at least) the same performance as the one we got in https://arxiv.org/abs/1911.01255. 

(please ignore the `release` in branch name, I meant `feature`)

### CODE REVIEW

**Review by hbredin — COMMENTED** [review]
Just went through changes of this huge PRs.
LGTM.

**Comment by hbredin** [comment]
Got approximately the same VAD and OSD results on DIHARD dataset

**Comment by mogwai** [comment]
Am I still going to try and reproduce the experiments for this?

**Comment by mogwai** [comment]
I can indeed, but it does raise the question of how we're publishing those docs?

**Comment by hbredin** [comment]
@mogwai Merging this big dirty PR that is probably impossible to review but did allow me to reach same results as v1 for VAD and OSD on DIHARD.

**Pull request merged**
