### PR TITLE
Doc: Add tutorial notebook for offline usage of `speaker-diarization-3.1`

### PR DESCRIPTION
**Pull request by simonottenhauskenbun**
Adds a tutorial notebook, explaining the intricacies of model naming for offline usage of the `speaker-diarization-3.1` pipeline.

Fixes https://github.com/pyannote/pyannote-audio/issues/1660

### CODE REVIEW

**Comment by hbredin** [comment]
Hey @simonottenhauskenbun it looks like I am not allowed to edit this PR.
Could you please [allow me](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to edit?

**Comment by simonottenhauskenbun** [comment]
> Hey @simonottenhauskenbun it looks like I am not allowed to edit this PR. Could you please [allow me](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to edit?

Hi @hbredin it seems like GitHub does not support this feature when the fork is under an organization, which it is in this case.
The documented check box does not appear for me on the side.

I think we have two options here:

1. If you need a simple change (e.g. rebase) I can do that.
2. If you want to edit yourself I think I need to fork pyannote-audio again under my account and create a new PR.

**Comment by hbredin** [comment]
Can we go with option 2 then?

**Comment by simonottenhauskenbun** [comment]
sure! I foreked the repo again under my personal account and now the button appeared:
grafik

PR is reopened and you should be able to edit.

**Comment by hbredin** [comment]
Thanks. Closing that one, then?

**Pull request closed without merging**
