### PR TITLE
Support MLflow along with Tensorboard for logging segmentation task visualizations during validation

### PR DESCRIPTION
**Pull request by entn-at**
When using PyTorch-Lightning's `MLFlowLogger` instead of `TensorBoardLogger` during training of segmentation models, the current implementation fails because MLflow's experiment tracking client has a different method for logging figures than Tensorboard. Unfortunately, PyTorch-Lightning doesn't abstract away this logger API difference.

Tested with MLflow and Tensorboard.

### CODE REVIEW

**Comment by hbredin** [comment]
Thanks for the PR...

... but don't you think it would be better to contribute to `pytorch-lightning` directly?

**Comment by entn-at** [comment]
Pytorch-lightning purposefully removed its partial image logging support less than a year ago (see https://github.com/Lightning-AI/lightning/pull/11857). The current PyAnnote code depends on the logger being an instance of TensorBoardLogger and will fail if it is not.

Alternatively, would it be an option to add a flag that controls whether figures are logged during the validation step? Just so that training doesn't fail.

**Comment by hbredin** [comment]
Thanks for the link to the `lightning` PR: I was missing this additionnal context to take a proper a decision. 

Merging as it is. Thanks @entn-at, this will be part of next release.

**Comment by entn-at** [comment]
Thanks @hbredin!

**Pull request merged**
