### PR TITLE
feat: send pipeline to device with Pipeline.to(device)

### PR DESCRIPTION
**Pull request by hbredin**
Fixes #1108 #1095 #1155 #1059 #1187

### CODE REVIEW

**Comment by prashanthellina** [comment]
@hbredin When I run the speaker diarization pipeline on latest `develop` branch, the GPU is not being used for embeddings computation (it used to work before the changes from this PR).

I suspect this piece of code in `speaker_verification.py` file.

https://github.com/pyannote/pyannote-audio/blob/40783ce0f81b8f7db2120546b6ce5c8e76b7753d/pyannote/audio/pipelines/speaker_verification.py#L260

When I change `self.device` to `device`, it works as expected.

**Comment by hbredin** [comment]
Good catch. Would you make a PR?

**Comment by prashanthellina** [comment]
Sure, Will do.

**Comment by prashanthellina** [comment]
@hbredin  https://github.com/pyannote/pyannote-audio/pull/1217

**Comment by maxiek0071** [comment]
@hbredin 

Would you mind telling how do I call `pipeline.to(device)` to decode on CPU?

This is my code:

```
from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization",
                                    use_auth_token="<my_token>")
pipeline = pipeline.to("cpu")
```

and am getting this error:

```Traceback (most recent call last):
  File "transcription_module/my_custom_example.py", line 18, in <module>
    pipeline = pipeline.to("cpu")
  File "/home/ubuntu/.local/lib/python3.7/site-packages/pyannote/pipeline/pipeline.py", line 100, in __getattr__
    raise AttributeError(msg)
AttributeError: 'SpeakerDiarization' object has no attribute 'to'
```

**Comment by hbredin** [comment]
`Pipeline.to` API has not been released yet.

Install `pyannote.audio` from `develop` branch and it should work.

**Comment by maxiek0071** [comment]
Thanks, it works now!

**Comment by lasagna0** [comment]
Hey, for me its not working when using pip install https://github.com/pyannote/pyannote-audio/archive/refs/heads/develop.zip

**Comment by donzthefonz** [comment]
I'm running Mac M1 and think I've installed the develop branch by running `pip install git+https://github.com/pyannote/pyannote-audio.git@develop#egg=pyannote-audio`

Does this mean it should automatically use the gpu/mps or do I have to manually set with `Pipeline.to("mps")`?

The diarization step is still taking longer than I would have expected it to. Though the audio file is 1.5 hours long...

**Comment by hbredin** [comment]
It will run on CPU by default.

**Comment by Qualzz** [comment]
Took me a while to notice this post. Nothing would work until I manually add pipeline.to(device) to my code. 

Is there any reason why it doesn't use the GPU by default since CPU would be extremely slow nonetheless ? 

Maybe i'm stupid, but I lost hours waiting the process to complete while it would took 300x less with my GPU. Tried multiple torch install, etc.

**Comment by lyehe** [comment]
Im having the same issue. The pipeline is running on the CPU by default. 
BTW, I also tried pipeline.to(device), which broke the kernel.

**Comment by go-merge** [comment]
> Im having the same issue. The pipeline is running on the CPU by default.
> BTW, I also tried pipeline.to(device), which broke the kernel.

Mac M2 Max, works 25times faster for 30sec audio
Image 12 09 2024 at 17 37

**Pull request merged**
