### PR TITLE
Replace np.NaN (deprecated in NumPy 2.0.0) with np.nan

### PR DESCRIPTION
**Pull request by ibevers**
See:
https://numpy.org/devdocs/release/2.0.0-notes.html

### CODE REVIEW

**Comment by egordorichev** [comment]
Ran into this issue ealier today, thanks for the pr!

**Comment by hbredin** [comment]
Thanks @ibevers! Will be part of next release!

**Comment by ibevers** [comment]
Great! Glad to hear that!

**Comment by metal3d** [comment]
It's actually wider...

```
 File "/XXX/venv/lib64/python3.12/site-packages/pyannote/audio/pipelines/speaker_diarization.py", lin
e 403, in reconstruct
    clustered_segmentations = np.NAN * np.zeros(
                              ^^^^^^
  File "/XXX/venv/lib64/python3.12/site-packages/numpy/__init__.py", line 410, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'NAN'. Did you mean: 'nan'?
```

**Pull request merged**
