### PR TITLE
improve: refactor DomainAdversarial and DomainAware

### LINKED ISSUE #215: Refactoring code between {DomainAdversarial,DomainAware}SpeechActivityDetection classes
As observed in PR https://github.com/pyannote/pyannote-audio/pull/211
The **DomainAwareSpeechActivityDetection** and **DomainAwareSpeechActivityDetection** classes from the **pyannote.audio.labeling.tasks.speech_activity_detection.py** file have almost the same **batch_loss** function.

The only differences between these 2 approaches lies on the sign of the gradient ! One might think about a better way to share code between these 2 classes. Maybe an abstract class **Branch** ? 🌳

### LINKED ISSUE #242: DomainAware has an error on develop branch
When I try to run a training for the `DomainAwareSpeechActivityDetection` with the current develop branch, I get this error:

``` 
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/train/schedulers.py", line 317, in on_train_start
    super().on_train_start(trainer)
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/train/schedulers.py", line 61, in on_train_start
    trainer.base_learning_rate_ = self.auto_lr(trainer)
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/train/schedulers.py", line 144, in auto_lr
    loss = trainer.batch_loss(batch)['loss']
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/labeling/tasks/speech_activity_detection.py", line 299, in batch_loss
    domain_scores = self.activation_(self.domain_classifier_(intermediate))
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/models/models.py", line 163, in forward
    output, hidden = self.rnn_(features)
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 559, in forward
    return self.forward_tensor(input, hx)
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 539, in forward_tensor
    output, hidden = self.forward_impl(input, hx, batch_sizes, max_batch_size, sorted_indices)
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 519, in forward_impl
    self.check_forward_args(input, hx, batch_sizes)
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 490, in check_forward_args
    self.check_input(input, batch_sizes)
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 149, in check_input
    expected_input_dim, input.dim()))
RuntimeError: input must have 3 dimensions, got 2
```

I don't know what is causing it yet, just creating the issue for reference

### PR DESCRIPTION
**Pull request by Mymoza**
**This PR is:**
-  Fix #215 : Tentative to refactor `DomainAwareSpeechActivityDetection` and `DomainAdversarialSpeechActivityDetection` as they were sharing code in `batch_loss` 
- Add some docstrings 
- Fix #242, I added a default pooling in `DomainAwareSpeechActivityDetection` but also a message to let the user know that the pooling was chosen for him/her. I didn't know if we preferred to use a default pooling or to raise an error. 

**How I tested these changes:** 
`pip install git+https://github.com/Mymoza/pyannote-audio.git@refactor-adversarial-aware`, then I ran these tests: 

- [x] I ran `DomainAdversarialSpeechActivityDetection` with only 2 epochs (`pyannote-speech-detection train --gpu --to=2 ${EXPERIMENT_DIR} ${PROTOCOL}`) as I figured it would be enough to just test and see if training still works. I compared the log with another training I did before the refactor and I don't see anything strange.

- [x] I also ran  `DomainAwareSpeechActivityDetection` with 2 epochs as well

- [x] Also ran with `SpeechActivityDetection` 2 epochs 

 Would any other test be useful to do in order to make sure this didn't break anything?

### CODE REVIEW

**Comment by hbredin** [comment]
@Mymoza I do not receive any notification when you edit the original comment above.
If you need feedback from me, please add a new comment

**Comment by Mymoza** [comment]
@hbredin OK! The PR is now ready for review when you get a chance. :)

**Comment by Mymoza** [comment]
@hbredin OK! The PR is now ready for review when you get a chance. :)

@MarvinLvn I would also appreciate your opinion on the fix for #242!

**Comment by hbredin** [comment]
Thanks @Mymoza

However, it feels like you stopped halfway!  
Why don't you also backport these two things to `DomainAwareSpeechActivityDetection`? 
- support for `alpha` parameter
- support for `MSELoss`

**Comment by Mymoza** [comment]
@hbredin You are right. I made those changes now. Let me know your comments! 

I know I could improve on documentation for this PR, but I don't have time at the moment (final exams), but I could open an issue to add documentation and would work on it after Christmas.

**Pull request closed without merging**
