### PR TITLE
fix: fix WeSpeakerPretrainedSpeakerEmbedding GPU support

### LINKED ISSUE #1475: pipeline.to(torch.device("cuda")) not working on T4 Tesla GPU (pyannote==3.0.0)
I've been testing out today the new pyannote 3.0.0 but it seems that adding 

`import torch
pipeline.to(torch.device("cuda"))`

to my code does not allocate the pipeline to the GPU anymore.

I have tried the following:

```
device = torch.device("cuda" if torch.cuda.is_available() else "cpu") # returns cuda
pipeline = Pipeline.from_pretrained(
    'pyannote/speaker-diarization-3.0',
    use_auth_token = 'key'
).to(device)

##########

device = torch.device("cuda" if torch.cuda.is_available() else "cpu") # returns cuda
pipeline = Pipeline.from_pretrained(
    'pyannote/speaker-diarization-3.0',
    use_auth_token = 'key'
).to(torch.device(device))

##########

pipeline = Pipeline.from_pretrained(
    'pyannote/speaker-diarization-3.0',
    use_auth_token = 'key'
)

pipeline = pipeline.to(torch.device("cuda:0"))
```
But nothing seems to work. 

When I type `pipeline.device` after applying the configuration, it returns `device(type='cuda')`, but it is still not using it. This is what the `nvidia-smi` returns WHILE THE PIPELINE IS RUNNING:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000001:00:00.0 Off |                  Off |
| N/A   43C    P0    27W /  70W |    855MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

Colab notebook to reproduce the issue (MRE): https://colab.research.google.com/drive/16zpDvNa5fUs8a_r-d-DxbdAdLHEPrgta?usp=sharing

PS: this was working with the Interspeech and 2022.07 checkpoints and the previous version.

Edit: I did some testing and the problem seems to be the embedding model, I tried using the "speechbrain/spkrec-ecapa-voxceleb" embedding model by editing the config.yaml file and, in this case, the GPU was properly used.

### PR DESCRIPTION
**Pull request by hbredin**
Should fix #1475 #1476 

I would love feedback from @doublex @guilhermehge @realfolkcode

### CODE REVIEW

**Review by realfolkcode — COMMENTED** [review]
I have modified the Colab MRE from #1475 to install this fix. Here is the [link](https://colab.research.google.com/drive/16zpDvNa5fUs8a_r-d-DxbdAdLHEPrgta?usp=sharing). However, it made the wall time even worse: 6m 45s. It allocates memory into VRAM but for some reason the embedding model is extremely slow.

onnxruntime-gpu version: 1.16.0
CUDA version: 11.8

**Comment by hbredin** [comment]
Thanks a lot. That really helped me narrow things down. 

I think the issue is that default `onnxruntime` behavior is to optimize the computation graph for each new input shape... and it happens that `pyannote` speaker diarization pipeline might use a lot of different shapes when processing a file.

https://github.com/microsoft/onnxruntime/issues/6978

I just pushed a new commit. Can you try again?

**Comment by guilhermehge** [comment]
I was testing the solution in an isolated environment using the docker image `nvidia/cuda:11.7.1-cudnn8-runtime-ubuntu20.04`.

First I tested only adding onnxruntime-gpu==1.16.0 to my requirements along with pyannote.audio==3.0.0, but the time didn't change and the GPU was not used.

Second, I tried using only this commit and it still got the same time and no gpu being used.

**Comment by guilhermehge** [comment]
@hbredin still not working with the new commit, I still get the same embedding time and the GPU is not being used. Here's a snippet of nvidia-smi while the embedding was at 40%

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000001:00:00.0 Off |                  Off |
| N/A   37C    P0    25W /  70W |   4863MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

I remind you that this is in an isolated environment using a docker container. The GPU works fine for the older diarization pipeline @2.1 and for the faster_whisper algorithm, but for the embedding model of the new pipeline, it does not work.

**Comment by hbredin** [comment]
That's weird because it solves the issue on Google Colab.
`pyannote/speaker-diarization-3.0` is even slightly faster than `pyannote/speaker-diarization-2.1`.

**Comment by hbredin** [comment]
I have no knowledge of `docker` containers.

Could it be something related to an incompatibility between `onnxruntime-gpu` and `docker/cuda` images? 

Are you 100% sure that it used the latest commit and no cache was used?

**Comment by guilhermehge** [comment]
Yes, I am sure, I rebuilt the image from scratch and checked if your commit was in fact in the code. I'll go check the colab with your solution. As you mentioned, the problem might be a dependency problem with the specific image that I'm using in docker. I'll check it out.

**Comment by guilhermehge** [comment]
Update: I did a pip install --force-reinstall onnxruntime-gpu and it worked on the docker container, but when loading the pipeline, I got the following warning:

`2023-09-27 15:15:43.525160455 [W:onnxruntime:, session_state.cc:1162 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-09-27 15:15:43.525193659 [W:onnxruntime:, session_state.cc:1164 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.` 

Do you know what it might be?

**Comment by guilhermehge** [comment]
Just as a sidenote, I believe your model will be used with faster_whisper, and using onnxruntime-gpu may make it incompatible with that library. I am going to run a few more tests and let you know my results, but, so far, faster_whisper stopped working when I uninstalled onnxruntime to leave only onnxruntime-gpu. Do you believe there is another alternative?

I posted [an issue on faster_whisper's repo](https://github.com/guillaumekln/faster-whisper/issues/493) to address the situation.

**Comment by hbredin** [comment]
> Do you believe there is another alternative? Like porting your model outside of onnx?

The point is that this is not **my** model. `pyannote` does not (yet) have a good speaker embedding model of its own. It uses external ones. 

Working on it, though ;-)

**Comment by guilhermehge** [comment]
Oh, fair enough, but is it possible to convert it for not using onnx?

**Comment by hbredin** [comment]
> Oh, fair enough, but is it possible to convert it for not using onnx?

Issue #1477 has already been opened related to this particular aspect.
Let's continue this discussion there. But, short answer: I don't (yet) know how to do that.

**Comment by hbredin** [comment]
I just released 3.0.1, including this fix.

**Comment by guilhermehge** [comment]
Awesome! Just checked pypi, great job! fyi, I believe it's not still showing on github's releases yet.

**Comment by hbredin** [comment]
FYI: https://github.com/pyannote/pyannote-audio/issues/1537

**Pull request merged**
